27/home/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'StraightAs'

urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('logout', views.logout_request, name='logout'),
    path('login', views.login_request, name='login'),
    path('changepassword', views.change_password, name='change_password'),
    path('dogodki', views.dogodki, name='dogodki'),
    path('dodajanjedogodkov', views.dodajanjedogodkov, name='dodajanjedogodkov'),
    path('dodajanjeobvestil', views.dodajanjeobvestil, name='dodajanjeobvestil'),
    path('home', views.home_pogled, name='home_pogled'),
    path('restavracije', views.food_pogled, name='food_pogled'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('delete_me', views.delete_on_post, name='delete_on_post'),
    path('calendarCreate', views.calendar_create_view, name='calendarCreate'),
    path('<int:id>/calendarEdit', views.calendar_update_view, name='calendarEdit'),
    path('<int:id>/calendarDelete', views.calendar_delete_view, name='calendarDelete'),
    path('timetableCreate/<int:dan>/<int:ura>', views.timetable_create_view, name='timetableCreate'),
    path('calendarSpecific/<str:dan>', views.calendar_specific_day_view, name='calendarSpecific'),
    path('<int:id>/timetableEdit', views.timetable_update_view, name='timetableEdit'),
    path('<int:id>/timetableDelete', views.timetable_delete_view, name='timetableDelete'),
    path('todoCreate', views.todo_create_view, name='todoCreate'),
    path('<int:id>/todoEdit', views.todo_update_view, name='todoEdit'),
    path('<int:id>/todoDelete', views.todo_delete_view, name='todoDelete'),
    path('bus', views.bus_search_view, name='bus'),
    path('busQuery/<str:query>', views.bus_search_query_view, name='busQuery'),
    path('restaurants/loc/<str:location>', views.restaurant_dropdown_reqeust, name='restLocation')
]

27/straightas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

27/home/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Koledar, Urnik, TODO, Dogodek
from colorfield.fields import ColorField


class DodajanjeDogodkaForm(forms.ModelForm):
    class Meta:
        model = Dogodek
        fields = ["ime", "datum", "organizator", "opis"]


class DodajanjeObvestilaForm(forms.Form):
    sporocilo = forms.CharField(widget=forms.Textarea)


class SignupForm(UserCreationForm):
    username = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class NewLoginForm(AuthenticationForm):
    username = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        fields = ("username", "password")

    def save(self, commit=True):
        user = super(NewLoginForm, self).save(commit=False)
        if commit:
            user.save()
        return user


class KoledarForm(forms.ModelForm):
    class Meta:
        model = Koledar
        fields = ["ime", "datum", "opis"]


class UrnikForm(forms.ModelForm):
    class Meta:
        model = Urnik
        fields = ["ime", "trajanje", "barva"]


class TODOForm(forms.ModelForm):
    class Meta:
        model = TODO
        fields = ["opis"]

27/home/views.py
from math import sqrt

from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, render_to_response
from django.template import RequestContext
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import Group
from . import models
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from . import forms
from .forms import SignupForm, NewLoginForm, KoledarForm, UrnikForm, TODOForm
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required, user_passes_test

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
import json


def prikazi_obvestila(request):
    vsa_obvestila = models.AdministratorskaObvestila.objects.all()
    vsa_obvestila_index = []
    for i in vsa_obvestila:
        vsa_obvestila_index.append(False)

    prikazana_sporocila = []
    prikazana_sporocila_indices = []
    index_obvestil = 0
    for o in vsa_obvestila:
        sporocilo = "Warning: " + o.sporocilo
        piskotki = request.COOKIES

        for cookie_name in piskotki.keys():
            if (sporocilo == piskotki[cookie_name]):
                vsa_obvestila_index[index_obvestil] = True
                # print("Found cookie in list")

        if (vsa_obvestila_index[index_obvestil] == False):
            messages.warning(request, sporocilo)
            prikazana_sporocila.append(sporocilo)
            prikazana_sporocila_indices.append(index_obvestil)

        index_obvestil += 1

    return prikazana_sporocila, prikazana_sporocila_indices


def obvestila_set_cookies(response, prikazana_sporocila, prikazana_sporocila_indices):
    index_sp = 0
    for sporocilo in prikazana_sporocila:
        response.set_cookie(str(prikazana_sporocila_indices[index_sp]), sporocilo)
        # print("cookie name: ", str(prikazana_sporocila_indices[index_sp]),   "  cookies set: ", sporocilo )
        index_sp += 1


def is_registered(user):
    return user.groups.filter(name='registriran').exists()


def is_upravljalec(user):
    return user.groups.filter(name='upravljalec').exists()


def is_admin(user):
    return user.groups.filter(name='admin').exists()


def is_not_logged_in(user):
    return user.is_anonymous


def index(request):
    return render(request=request, template_name='index.html')
    

@login_required(login_url='/register')
@user_passes_test(is_registered)
def dogodki(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    response = render(request=request,
                      template_name='EventsPogled.html',
                      context={'dogodki': models.Dogodek.objects.all})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@login_required(login_url='/register')
def delete_on_post(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    template = "HomePogled.html"

    if request.method == "POST":
        print(request.POST.get('podatki'))

    response = redirect('/home')
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@login_required(login_url='/register')
@user_passes_test(is_registered)
def home_pogled(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    response = render(request=request,
                      template_name="HomePogled.html",
                      context={'koledarski_vnosi': models.Koledar.objects.filter(author=request.user),
                               'urnik_vnosi': models.Urnik.objects.filter(author=request.user),
                               'todo_vnosi': models.TODO.objects.filter(author=request.user)})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


def food_pogled(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    all_objs = models.Restavracija.objects.all()
    restaurants_sorted = sorted(all_objs, key=lambda h: h.ime)
    # distances = [sqrt((r.lat - 46.051120) ** 2 + (r.long - 14.467210) ** 2) for r in all_objs]
    #     # sort_idx = [i[0] for i in sorted(enumerate(distances), key=lambda x: x[1])]
    #     # restaurants_sorted = [all_objs[i] for i in sort_idx]
    response = render(request=request,
                      template_name='FoodPogled.html',
                      context={'restavracije': restaurants_sorted})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@login_required(login_url='/register')
@user_passes_test(is_upravljalec)
def dodajanjedogodkov(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    if request.method == "POST":
        form = forms.DodajanjeDogodkaForm(request.POST)
        if form.is_valid():
            # Naredimo nov dogodek
            ime = form.cleaned_data.get('ime')
            datum = form.cleaned_data.get('datum')
            organizator = form.cleaned_data.get('organizator')
            opis = form.cleaned_data.get('opis')
            nov_dogodek = models.Dogodek(ime=ime, datum=datum, organizator=organizator, opis=opis)
            nov_dogodek.save()  # in ga shranimo v bazo

    form = forms.DodajanjeDogodkaForm()
    response = render(request=request,
                      template_name="UpravljalcevPogled.html",
                      context={"form": form,
                               'dogodki': models.Dogodek.objects.all})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@login_required(login_url='/register')
@user_passes_test(is_admin)
def dodajanjeobvestil(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    if request.method == "POST":
        form = forms.DodajanjeObvestilaForm(request.POST)
        if form.is_valid():
            # Naredimo nov dogodek
            sporocilo = form.cleaned_data.get('sporocilo')
            novo_obvestilo = models.AdministratorskaObvestila(sporocilo=sporocilo)
            novo_obvestilo.save()  # in ga shranimo v bazo
        return redirect('/dodajanjeobvestil')

    form = forms.DodajanjeObvestilaForm()
    response = render(request=request,
                      template_name="AdminPogled.html",
                      context={"form": form})

    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@user_passes_test(is_not_logged_in)
def register(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    if request.method == "POST":
        # form = NewUserForm(request.POST)
        form = SignupForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # Oznacimo ga kot registriran uporabnik, admin in upravljalec sta rocno dodana v http://127.0.0.1:8000/admin
            registered_group = Group.objects.get(name='registriran')
            new_user.groups.add(registered_group)
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your StraightAs account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('username')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request, "Please confirm your email address to complete the registration")
        else:
            response = render(request=request,
                              template_name="register.html",
                              context={"form": form})
            obvestila_set_cookies(response, obvestila, obvestila_indices)
            return response

    form = SignupForm()
    response = render(request=request,
                      template_name="register.html",
                      context={"form": form})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


@user_passes_test(is_not_logged_in)
def login_request(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    if request.method == "POST":
        form = NewLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                response = redirect("StraightAs:index")
                obvestila_set_cookies(response, obvestila, obvestila_indices)
                return response
            else:
                messages.error(request, "Invalid username or password")
        else:
            messages.error(request, "Invalid username or password")

    form = NewLoginForm()
    response = render(request,
                      template_name="login.html",
                      context={"form": form})
    obvestila_set_cookies(response, obvestila, obvestila_indices)
    return response


def logout_request(request):
    obvestila, obvestila_indices = prikazi_obvestila(request)
    logout(request)
    messages.info(request, "Logged out successfully!")

27/home/templates/AdminPogled.html
{% extends 'header.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button onclick="document.getElementById('id_sporocilo').value = '';" class="btn btn-outline-info">Cancel</button>
    <button class="btn btn-outline-info" type="submit">Post message</button>
</form>
{% endblock %}

27/home/templates/BusResults.html
<div style="margin: 1rem">
    {% if error == true %}
    <h4>There is no station with this name or id!</h4>
    {% else %}
    <ul >
        {% for station in postaje %}
            <li class="collection-item">
                <h4>{{ station.ime | safe }}</h4>
                <table>
                    <thead>
                        <tr>
                            <td>Num</td>
                            <td>Direction</td>
                            <td>Arrivals</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bus in station.busi %}
                        <tr>
                            <td>{{ bus.num | safe }}</td>
                            <td>{{ bus.end | safe }}</td>
                            <td>{{ bus.arrivals | safe }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

27/home/templates/DeleteForm.html
<div style="margin: 1rem">
    <h5>Are you sure you want to delete selected entry?</h5>
    {% if form.errors.non_field_errors %}
      {{ form.errors.non_field_errors }}
    {% endif %}
    <form method="POST" action="{{ actionUrl }}">
      {% csrf_token %}
      <button class="btn waves-effect waves-light" type="submit" name="action">
          YES
      </button>
      <a class="btn waves-effect waves-light" href="{% url 'StraightAs:home_pogled' %}">NO</a>
    </form>
</div>

27/home/templates/FoodPogled.html
{% extends 'header.html' %}

{% block content %}
<h1>Restaurants</h1>
<br>
<div class="row">
    <div class="col s6" style="text-align: center">
        <div id="map" style="height: 400px;width: 100%;" class="container"></div>
        <script>
            var map = 0;
            var geocoder;
            var address = "Ljubljana";
            var latitude_global;
            var longitude_global;


              function initMap() {
                if(map !== 0) {return;}  // Already defined
                map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 8,
                  center: {lat: 46.0569, lng: 14.5058}
                });
                geocoder = new google.maps.Geocoder();
                // Try HTML5 geolocation.
                if (navigator.geolocation) {
                  navigator.geolocation.getCurrentPosition(function(position) {
                    var pos = {
                      lat: position.coords.latitude,
                      lng: position.coords.longitude
                    };

                    // infoWindow.setPosition(pos);
                    // infoWindow.setContent('Location found.');
                    // infoWindow.open(map);
                    map.setCenter(pos);
                    showUserLocationMarker(map, pos);
                    map.setZoom(16);

                    var myNode = document.getElementById("restaurant_dropdown");

                    var cNode = myNode.cloneNode(false);
                    myNode.parentNode.replaceChild(cNode, myNode);

                    var url = "{% url 'StraightAs:restLocation' location=123 %}";
                    var location = position.coords.latitude.toString() + "$" + position.coords.longitude.toString();
                    var finalUrl = url.replace('123', location);
                    $('.dd-res').load(finalUrl);
                  }, function() {});
                }
              }

            function showUserLocationMarker(map_obj, user_loc) {
              var marker = new google.maps.Marker({
                      map: map_obj,
                      position: user_loc,
                      icon: {
                        url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
                      }
              });
            }

            function createRestaurantMarker(lat_data, long_data, rname, raddr, ropens, rdoplacilo) {
                var markerPos = {lat: lat_data, lng: long_data};
                // map.setCenter(markerPos);
                var marker = new google.maps.Marker({
                    map: map,
                    position: markerPos,
                    restaurant_data: [rname, raddr, ropens, rdoplacilo],
                    title: rname,
                    icon: {
                        url: "http://maps.google.com/mapfiles/ms/icons/red-dot.png"
                    }
                });
                google.maps.event.addListener(marker, 'click', function() {
                    centerMapOnLoc(lat_data, long_data);
                    displayRestaurantInfo(marker.restaurant_data[0], marker.restaurant_data[1], marker.restaurant_data[2], marker.restaurant_data[3])
                });
            }

            function displayRestaurantInfo(restaurant_name_str, addr, opens, cost) {
                document.getElementById("restaurantname").innerHTML = "Restaurant: <strong>" + restaurant_name_str + "</strong>";
                document.getElementById("restaurantaddr").innerHTML = "Address: <strong>" + addr + "</strong>";
                document.getElementById("restaurantopens").innerHTML = "Opening time: <strong>" + opens + "</strong>";
                document.getElementById("restaurantcost").innerHTML = "Cost: <strong>" + cost + "</strong>";
            }

            function centerMapOnLoc(lat, lng) {
                map.setCenter({lat:lat, lng:lng});
            }
        </script>

        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVnxI1Ax2He_4FtmFlj-1zgvulC9mkHJQ&callback=initMap"></script>
    </div>
    <div class="col s6" style="text-align: center">
        <div class="row" style="height: 200px; width: 100%">
            <!-- Dropdown Structure -->
            <ul id='restaurant_dropdown' class='dropdown-content dd-res' style="min-width: 20%; max-height: 20%;">
                {% for r in restavracije %}
                <li><a id="restaurantclick"
                       href="#"
                       onclick="centerMapOnLoc(parseFloat('{{ r.lat }}'), parseFloat('{{ r.long }}'));displayRestaurantInfo('{{ r.ime }}', '{{ r.naslov }}', '{{ r.odpiralni_cas | linebreaks }}', '{{ r.doplacilo }}');return false;">{{ r.ime }}</a>
                    <script>createRestaurantMarker(parseFloat('{{ r.lat }}'), parseFloat('{{ r.long }}'), '{{ r.ime }}', '{{ r.naslov }}', '{{ r.odpiralni_cas | linebreaks }}', '{{ r.doplacilo }}');</script>
                </li>
                {% endfor %}
            </ul>
            <!-- Dropdown Trigger -->
            <a class='dropdown-trigger btn' href='#' data-target='restaurant_dropdown'>Restaurants</a>
        </div>
        <div class="row" style="height: 200px;">
            <p id="restaurantname">Restaurant name</p>
            <p id="restaurantaddr">Restaurant address</p>
            <p id="restaurantopens">Opening time</p>
            <p id="restaurantcost">Meal cost</p>
        </div>
    </div>
</div>
<script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.dropdown-trigger');
            var instances = M.Dropdown.init(elems);
        });
</script>
{% endblock %}

27/home/templates/KoledarForm.html
<div style="margin: 1rem" id="one">
    <h5>Dodaj vnos v koledar</h5>
    {% if form.errors.non_field_errors %}
      {{ form.errors.non_field_errors }}
    {% endif %}
    <form id="form-koledar-create" method="POST" action="{% url 'StraightAs:calendarCreate' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.source.errors }}
        {{ form.source }}
        <!--Form content-->
        {{form.as_p}}
        <!--Form button-->
        <button id="submitButton" class="btn" type="submit" name="action">
          CREATE
        </button>
        <p id="errorText"></p>
    </form>
</div>
<script>

    function daysInMonth(m, y) {
        switch (m) {
            case 1 :
                return (y % 4 == 0 && y % 100) || y % 400 == 0 ? 29 : 28;
            case 8 : case 3 : case 5 : case 10 :
                return 30;
            default :
                return 31
        }
    };

    function isValidDate(d, m, y) {
        return m >= 0 && m <= 12 && d > 0 && d <= daysInMonth(m, y) && y >= 1000 && y < 10000;
    };

    function isValidTime(h, m, s){
      return h >= 0 && h < 24 && m >= 0 && m < 60 && s >= 0 && s < 60;
    }
    
    $('#form-koledar-create').submit(function() {
      var form = document.getElementById("form-koledar-create")
      var date = form.elements["datum"].value

      var numPattern = /^[0-9\-\:\ ]+$/;
      if(!numPattern.test(date)){
        showErrorMsg();
        return false;
      }

      var splittedDate = date.split(" ")
      if(splittedDate.length != 2){
        showErrorMsg();      
        return false;
      }

      var datum = splittedDate[0];
      var time = splittedDate[1];

      var datePattern = /^[0-9\-]+$/;
      var timePattern = /^[0-9\:]+$/;
      if(!datePattern.test(datum) || !timePattern.test(time)){
        showErrorMsg();
        return false;
      }

      var datumSplitted = datum.split("-");
      var timeSplitted = time.split(":")
      if(datumSplitted.length != 3 || timeSplitted.length != 3){
        showErrorMsg();
        return false;
      }

      var year = datumSplitted[0];
      var month = datumSplitted[1];
      var day = datumSplitted[2];
      var hour = timeSplitted[0];
      var minute = timeSplitted[1]; 
      var second = timeSplitted[2];

      if(!isValidDate(day, month, year) || !isValidTime(hour, minute, second)){
        showErrorMsg();
        return false;
      }
      
      return true;
    });

    function showErrorMsg(){
        document.getElementById("submitButton").classList.add("red");
        document.getElementById("submitButton").classList.add("lighten-1");
        document.getElementById("errorText").innerHTML = "ERROR: Wrong date and/or time!";
    }
</script>

27/home/templates/KoledarSpecific.html
<div style="margin: 1rem">
    <h5>Events for selected day:</h5>
    <ul class="collection">
        {% for vnos in vnosi %}
            <li class="collection-item">
                <p><p><strong style="font-size: 200%">{{ vnos.ime | safe }}</strong></p>
                    Datum: {{ vnos.datum | date:'d. m. Y H:i' | safe }}<br>
                    Opis: {{ vnos.opis | safe }}<br>
                </p>
                <a class="btn modal-trigger red lighten-2" id="deleteCalendarEvent{{vnos.id | safe }}" href="#modalCalendar">Del</a>
                <a class="btn modal-trigger deep-purple lighten-2" id="editCalendarEvent{{vnos.id | safe }}" href="#modalCalendar">Edit</a>
            </li>
            <script>
                document.getElementById('editCalendarEvent{{vnos.id | safe }}').addEventListener("click", function(event) {
                    event.preventDefault();

                    $('.modalCalendar').modal({
                        onOpenStart : function () {
                            $('#modalCalendarBase').modal("close");
                        },
                            onCloseEnd : function () {
                            var lo = window.location.href.split("/");
                            lo[lo.length-1] = "home"
                            lo = lo.join("/")
                            console.log(lo)
                            window.location.replace(lo);
                        }
                    });
                    var url = "{% url 'StraightAs:calendarEdit' id=123 %}";
                    var finalUrl = url.replace('123', {{vnos.id | safe }});
                    $('.modal-content-Calendar').load(finalUrl);

                    location.hash = event.target.getAttribute('href').substr(1);
                });

                document.getElementById('deleteCalendarEvent{{vnos.id | safe }}').addEventListener("click", function(event) {
                    event.preventDefault();

                    $('.modalCalendar').modal({
                        onOpenStart : function () {
                            $('#modalCalendarBase').modal("close");
                        },
                        onCloseEnd : function () {
                            console.log("whaaat")
                            var lo = window.location.href.split("/");
                            lo[lo.length-1] = "home"
                            lo = lo.join("/")
                            console.log(lo)
                            window.location.replace(lo);
                        }
                    });
                    var url = "{% url 'StraightAs:calendarDelete' id=123 %}";
                    var finalUrl = url.replace('123', {{vnos.id | safe }});
                    $('.modal-content-Calendar').load(finalUrl);

                    location.hash = event.target.getAttribute('href').substr(1);
                });
            </script>
        {% endfor %}
    </ul>
</div>

27/home/templates/TimetableForm.html
<div style="margin: 1rem">
<h5>Add timetable entry</h5>
{% if form.errors.non_field_errors %}
  {{ form.errors.non_field_errors }}
{% endif %}
<form id="form123" method="POST" action="{{ action_url }}">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {{ form.source.errors }}
  {{ form.source }}
  <!--Form content-->
  {{form.as_p}}
  <!--Form button-->
  <button id="submitButton123" class="btn" type="submit" name="action">
      CREATE
  </button>
  <p id="errorText123"></p>
</form>
</div>
<script>
  var ura = parseInt('{{ ura }}');
  var dan = parseInt('{{ dan }}');

  var events = [];
  var eventDays = [
    {% for v in vnosi %}
      '{{ v.dan }}',
    {% endfor %}
  ]

  var eventStarts = [
  {% for v in vnosi %}
      '{{ v.ura }}',
    {% endfor %}
  ]

  for (var i = 0; i < eventDays.length; i++) {
    events.push({
      day: eventDays[i],
      start: eventStarts[i]
    });
  }

  $('#form123').submit(function() {
    var form = document.getElementById("form123")
    var color = form.elements["barva"].value
    var trajanje = Number(form.elements["trajanje"].value)
    if(color.substring(0, 1) == '#'){
      color = color.substring(1);
      form.elements["barva"].value = color; 
    }

    errorString = "";
    
    var isOk  = /(^[0-9A-F]{6}$)|(^[0-9A-F]{3}$)/i.test(color);
    if(!isOk){
      if(errorString == "") errorString += "ERROR: ";
      errorString += "wrong color (has to be in hex without #), ";
    }
    if(trajanje < 1 || trajanje > 17){
      if(errorString == "") errorString += "ERROR: ";
      errorString += "event can last between 1 and 16 hours, ";
    }
    if(ura + trajanje > 23){
      if(errorString == "") errorString += "ERROR: ";
      errorString += "event can only be in 1 day, ";
    }
    if(checkOverlap(trajanje)){
      if(errorString == "") errorString += "ERROR: ";
      errorString += "events overlap.";
    }

    if(errorString != ""){
      showErrorMsg(errorString);
      return false;
    }

    return true; // return false to cancel form action
  });

  function checkOverlap(trajanje){
    for(var i = 0; i < events.length; i++){
      if(events[i].day == dan){
        if(ura < events[i].start && ura + trajanje > events[i].start){
          return true;
        }
      }
    }

    return false;
  }

  function showErrorMsg(errormsg){
      document.getElementById("submitButton123").classList.add("red");
      document.getElementById("submitButton123").classList.add("lighten-1");
      document.getElementById("errorText123").innerHTML = errormsg;
  }
</script>

27/home/templates/TodoFormEdit.html
<div style="margin: 1rem" id="one">
    <h5>Edit TODO</h5>
    {% if form.errors.non_field_errors %}
      {{ form.errors.non_field_errors }}
    {% endif %}
    <form method="POST" action="{{ actionUrl }}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {{ form.source.errors }}
        {{ form.source }}
        <!--Form content-->
        {{form.as_p}}
        <!--Form button-->
        <button class="btn" type="submit" name="action">
          UPDATE
        </button>
        <a class="btn red lighten-2" id="todoDelete">Del</a>
    </form>
</div>
<script>
  document.getElementById('todoDelete').addEventListener("click", function(event){
    // console.log("tlelele sem")
    // var modalEl = document.getElementById('modalTodo');
    // var instance = M.Modal.getInstance(modalEl);
    // instance.close();
    var myNode = document.getElementById("modalTodoContent")
    var cNode = myNode.cloneNode(false);
    myNode.parentNode.replaceChild(cNode, myNode);
    
    var url = "{{ deleteUrl }}";
    $('#modalTodoContent').load(url);

    // modalEl = document.getElementById('modalTodoDelete');
    // instance = M.Modal.getInstance(modalEl);
    // instance.open();

    // location.hash = event.target.getAttribute('href').substr(1);

  })
</script>

27/home/templates/acc_active_email.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'StraightAs:activate' uidb64=uid token=token %}
{% endautoescape %}

27/home/templates/index.html
{% extends 'header.html' %}
{% block content %}

<div class="container" style="text-align: center">
    <h1 style="margin-top: 15rem">Welcome to StraightAS!!!</h1>
    <h5>
        Your one stop shop for all thing student ╚(ಠ_ಠ)=┐
    </h5>
</div>

{% endblock %}